export enum AccessChainFlagBits
{
    ACCESS_CHAIN_INDEX_IS_LITERAL_BIT = 1 << 0,
    ACCESS_CHAIN_CHAIN_ONLY_BIT = 1 << 1,
    ACCESS_CHAIN_PTR_CHAIN_BIT = 1 << 2,
    ACCESS_CHAIN_SKIP_REGISTER_EXPRESSION_READ_BIT = 1 << 3,
    ACCESS_CHAIN_LITERAL_MSB_FORCE_ID = 1 << 4,
    ACCESS_CHAIN_FLATTEN_ALL_MEMBERS_BIT = 1 << 5,
    ACCESS_CHAIN_FORCE_COMPOSITE_BIT = 1 << 6
}